### ISSUE TITLE
How might one insert a function at the end of a class?

### ISSUE THREAD

**Issue by mattpenner** [rioj7/my-code-actions#1]
I found your extension through your great [answer here on SO](https://stackoverflow.com/questions/65971560/vs-code-how-to-create-a-method-from-angular-html-template?answertab=active#tab-top).

Similar to the OP on that question I'm trying to add a new function to an Angular typescript class when clicking on the click handler in the corresponding html file. However, using your suggestion settings the function appears at the very top of the file, which breaks the code.

Ideally (for me) I would like it to appear at the end, but inside the class; i.e. the last function in the class.  Assuming I had only one class in the file I'm thinking a `"where":"beforeLast"` option would work if I had `"insertFind":"}"`.

Does this make sense or do you have a better suggestion for inserting the new function at the end of the class?

I.e.
```
import xxx;
import yyy;
@Component({
    selector: 'about',
    templateUrl: './about.component.html',
    styleUrls: ['./about.component.css']
})
export class AboutComponent {
    constructor() {
    }

    function() {
        somecode;
    }

    newlyInsertedFunction() {
    }
}

```

**Comment by mattpenner** [comment]
I added a pull request that enables the beforeLast functionality.  Here is an example settings config that adds a new typescript function just before the end of the class:
```
    "[html]": {
      "Create function {{atCursor:$1}}": {
        "file": "${fileBasenameNoExtension}.ts",
        "atCursor": "\\(click\\)=\"([^\"]+)\\(\\)\"",
        "text": "\n{{atCursor:$1}}() {\n}\n",
        "where": "beforeLast",
        "insertFind": "}"
      }
    }
```

**Comment by rioj7** [comment]
@mattpenner Try v0.7.0

**Comment by mattpenner** [comment]
Works great! Thx for merging my pull request. Was excited to see vscode already prompting me to reload for v0.7 testing it out.
