### ISSUE TITLE
Create function does not work

### ISSUE THREAD

**Issue by ngabello** [rioj7/my-code-actions#5]
After installing the extension and adding 
```
"my-code-actions.actions": {
    "[html]": {
      "Create function {{atCursor:$1}}": {
        "file": "${fileBasenameNoExtension}.ts",
        "atCursor": "\\(click\\)=\"([^\"]+)\\(\\)\"",
        "text": "function {{atCursor:$1}}() {\n}\n\n"
      }
    }
  }
``` 
to the settings file it shows the option to create the function but when I click on it, it does nothing. Am I doing something wrong?

**Comment by ngabello** [comment]
Ahh, I see it at the very top of the file and not associated to the component at all, guess I need to figure out how to create a public method in the component itself.

**Comment by rioj7** [comment]
@ngabello You need to define the `where` and `insertFind` properties.

Maybe you have to use the `edits` property to also create the place where you want to insert this function if not exist.

use the triple backtick if you want to show some piece of code in github issues. See the edit I made to the initial post.

**Comment by ngabello** [comment]
I came up with this
```
“my-code-actions.actions”: {
    “[html]“: {
      “Create method {{atCursor:$1}}“: {
        “file”: “${fileBasenameNoExtension}.ts”,
        “atCursor”: “\\(click\\)=\“([^\“]+)\\(\\)\“”,
        “text”: “\n  /**\n   *\n   */\n  public {{atCursor:$1}}(): void {}\n”,
        “action”: “insert”,
        “where”: “beforeLast”,
        “insertFind”: “}”
      }
    }
  }
```

**Comment by rioj7** [comment]
@ngabello Does this mean you have it working now?
